spring:
  application:
    name: backend
  profiles:
    active: local


# -- mybatis 설정 --
mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: com.ssafy.backend
  configuration:
    map-underscore-to-camel-case: true

# -- Swagger 설정 --
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    doc-expansion: none

server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

app:
  auth:
    email:
      code-expiration-minutes: 5

jwt:
  expiration: 3600000
