spring:
  application:
    name: backend
  profiles:
    active: local
# -- SMTP 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: danaazzang@gmail.com
    password: Danzzang1?
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# -- mybatis 설정 --
mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: com.ssafy.backend
  configuration:
    map-underscore-to-camel-case: true


# -- swagger 설정--

springdoc:
  swagger-ui:
    path: /swagger-ui
    groups-order: DESC               # path, query, body, response 순 출력
    tags-sorter: alpha               # 태그를 알파벳 순으로 정렬
    operations-sorter: method        # delete - get - path - post - put 순
    display-request-duration: true   # 응답시간 표시 여부
    doc-expansion: none              # api 목록 토글 형식이 펼칠지 접을지 설정

